In [1]:

import pandas as pd
import numpy as np
#pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('max_colwidth', 200)
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))


def df_stats(df):
    from tabulate import tabulate
    print("\n***** Shape: ", df.shape," *****\n")
    
    columns_list = df.columns.values.tolist()
    isnull_list = df.isnull().sum().values.tolist()
    isunique_list = df.nunique().values.tolist()
    dtypes_list = df.dtypes.tolist()
    
    list_stat_val = list(zip(columns_list, isnull_list, isunique_list, dtypes_list))
    df_stat_val = pd.DataFrame(list_stat_val, columns=['Name', 'Null', 'Unique', 'Dtypes'])
    print(tabulate(df_stat_val, headers='keys', tablefmt='psql'))
    return df.head()

/tmp/ipykernel_3451469/3295288443.py:8: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [7]:
df = pd.read_parquet('output/mimic_test_complete_qa_dataset.parquet')

# Sample up to 3 examples per prompt_type
sampled_df = (
    df.groupby('prompt_type', group_keys=False)
    .apply(lambda x: x.sample(n=min(3, len(x)), random_state=42))
    .reset_index(drop=True)
)

print("Sampled examples (up to 3 per prompt_type):")
display(sampled_df.head())
display(sampled_df[['prompt', 'report', 'prompt_type', 'generated_answer']])

FileNotFoundError: [Errno 2] No such file or directory: 'output/mimic_test_complete_qa_dataset.parquet'

In [64]:
df_mimic = pd.read_parquet('/media/data1/datasets/MIMIC-IV/Diagnosis/mimic_labelbox_bert_v4_all.parquet')
# Extract npy ID from the file path (the filename without extension)
df['waveform_npy_id'] = df['waveform_path_psa'].str.extract(r'/([^/]+)\.npy$')[0]
df_mimic['npy_id'] = df_mimic['npy_path'].str.extract(r'/([^/]+)\.npy$')[0]

display(df[['waveform_path_psa', 'waveform_npy_id']].head())
display(df_mimic[['npy_path', 'npy_id']].head())

                                                   waveform_path_psa waveform_npy_id
0  /media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy        40000079
1  /media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy        40000079
2  /media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy        40000079
3  /media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy        40000079
4  /media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy        40000079

                                                                        npy_path    npy_id
0  /media/data1/ravram/MIMIC-IV/1.0/files/p1000/p10000032/s40689238/40689238.npy  40689238
1  /media/data1/ravram/MIMIC-IV/1.0/files/p1000/p10000032/s44458630/44458630.npy  44458630
2  /media/data1/ravram/MIMIC-IV/1.0/files/p1000/p10000032/s49036311/49036311.npy  49036311
3  /media/data1/ravram/MIMIC-IV/1.0/files/p1000/p10000117/s45090959/45090959.npy  45090959
4  /media/data1/ravram/MIMIC-IV/1.0/files/p1000/p10000117/s48446569/48446569.npy  48446569

In [65]:
display(df_mimic.head(n=1))

,gender,age_at_ecg,diagnosis,npy_path,rr_interval,p_onset,p_end,qrs_onset,qrs_end,t_end,p_axis,qrs_axis,t_axis,new_PatientID,Bifid,RaVL + SV3 > 28 mm (H) or 20 mm (F),"Hyperacute T wave (lateral, V5-V6)","Hyperacute T wave (septal, V1-V2)",ST depression et T inversion in V5 or V6,Large >0.08 s,"Hyperacute T wave (anterior, V3-V4)",Auricular bigeminy,Biphasic,Ventricular bigeminy,J wave,Tall >2.5 mm,Sinus Pause,Dextrocardia,ST depression (posterior - V7-V8-V9),Poor quality,annotated_by_labelbox,complete_annotation,split_diagnosis,diagnosis_y,Acute pericarditis,QS complex in V1-V2-V3,T wave inversion (anterior - V3-V4),Right atrial enlargement,2nd degree AV block - mobitz 1,Left posterior fascicular block,Wolff-Parkinson-White (Pre-excitation syndrome),Junctional rhythm,Premature ventricular complex,rSR' in V1-V2,Right superior axis,"ST elevation (inferior - II, III, aVF)",Afib,ST elevation (anterior - V3-V4),RV1 + SV6 > 11 mm,Sinusal,Monomorph,Delta wave,R/S ratio in V1-V2 >1,Third Degree AV Block,LV pacing,Nonspecific intraventricular conduction delay,"ST depression (inferior - II, III, aVF)",Regular,Premature atrial complex,2nd degree AV block - mobitz 2,Left anterior fascicular block,Q wave (septal- V1-V2),Prolonged QT,Left axis deviation,Left ventricular hypertrophy,ST depression (septal- V1-V2),Supraventricular tachycardia,Atrial paced,"Q wave (inferior - II, III, aVF)",no_qrs,"T wave inversion (lateral -I, aVL, V5-V6)",Right bundle branch block,ST elevation (septal - V1-V2),SV1 + RV5 or RV6 > 35 mm,Right axis deviation,RaVL > 11 mm,Polymorph,Ventricular tachycardia,QRS complex negative in III,"ST depression (lateral - I, avL, V5-V6)",1st degree AV block,Lead misplacement,Q wave (posterior - V7-V9),Atrial flutter,Ventricular paced,ST elevation (posterior - V7-V8-V9),Ectopic atrial rhythm (< 100 BPM),Early repolarization,Ventricular Rhythm,Irregularly irregular,Atrial tachycardia (>= 100 BPM),R complex in V5-V6,"ST elevation (lateral - I, aVL, V5-V6)",Brugada,Bi-atrial enlargement,"Q wave (lateral- I, aVL, V5-V6)",ST upslopping,"T wave inversion (inferior - II, III, aVF)",Regularly irregular,Bradycardia,"qRS in V5-V6-I, aVL",Q wave (anterior - V3-V4),Acute MI,ST depression (anterior - V3-V4),Right ventricular hypertrophy,T wave inversion (septal- V1-V2),ST downslopping,Left bundle branch block,Low voltage,U wave,Left atrial enlargement,pid,npy_id
0,F,52,Sinus rhythm;Possible right atrial abnormality;Borderline ECG,/media/data1/ravram/MIMIC-IV/1.0/files/p1000/p10000032/s40689238/40689238.npy,659,40,128,170,258,518,81,77,79,10000032,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,"[sinus rhythm, possible right atrial abnormality, borderline ecg]",Sinus rhythm;Possible right atrial abnormality;Borderline ECG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11000000,40689238

In [66]:
# Drop the 'question' column from df before merging
#df = df.drop(columns=['question'])
cols_to_keep = ['gender','age_at_ecg','rr_interval', 'p_onset', 'p_end', 'qrs_onset', 'qrs_end', 't_end', 'p_axis', 'qrs_axis', 't_axis', 'new_PatientID', 'npy_id']
merged_df = df.merge(df_mimic[cols_to_keep], how='left', left_on='waveform_npy_id', right_on='npy_id')
display(merged_df.head())

,waveform_path_psa,report,Sinusal,Regular,Monomorph,QS complex in V1-V2-V3,R complex in V5-V6,"T wave inversion (inferior - II, III, aVF)",Left bundle branch block,RaVL > 11 mm,SV1 + RV5 or RV6 > 35 mm,"T wave inversion (lateral -I, aVL, V5-V6)",T wave inversion (anterior - V3-V4),Left axis deviation,Left ventricular hypertrophy,Bradycardia,"Q wave (inferior - II, III, aVF)",Afib,Irregularly irregular,Atrial tachycardia (>= 100 BPM),Nonspecific intraventricular conduction delay,Premature ventricular complex,Polymorph,T wave inversion (septal- V1-V2),Right bundle branch block,Ventricular paced,ST elevation (anterior - V3-V4),ST elevation (septal - V1-V2),1st degree AV block,Premature atrial complex,Atrial flutter,rSR' in V1-V2,"qRS in V5-V6-I, aVL",Left anterior fascicular block,Right axis deviation,2nd degree AV block - mobitz 1,"ST depression (inferior - II, III, aVF)",Acute pericarditis,"ST elevation (inferior - II, III, aVF)",Low voltage,Regularly irregular,Junctional rhythm,Left atrial enlargement,"ST elevation (lateral - I, aVL, V5-V6)",Atrial paced,Right ventricular hypertrophy,Delta wave,Wolff-Parkinson-White (Pre-excitation syndrome),Prolonged QT,ST depression (anterior - V3-V4),QRS complex negative in III,"Q wave (lateral- I, aVL, V5-V6)",Supraventricular tachycardia,ST downslopping,"ST depression (lateral - I, avL, V5-V6)",2nd degree AV block - mobitz 2,U wave,R/S ratio in V1-V2 >1,RV1 + SV6 > 11 mm,Left posterior fascicular block,Right atrial enlargement,ST depression (septal- V1-V2),Q wave (septal- V1-V2),Q wave (anterior - V3-V4),ST upslopping,Right superior axis,Ventricular tachycardia,ST elevation (posterior - V7-V8-V9),Ectopic atrial rhythm (< 100 BPM),Lead misplacement,Third Degree AV Block,Acute MI,Early repolarization,Q wave (posterior - V7-V9),Bi-atrial enlargement,LV pacing,Brugada,Ventricular Rhythm,no_qrs,dataset,waveform_name,waveform_path_original,gender_x,age_at_ecg_x,rr_interval_x,prompt,prompt_category,prompt_weight,prompt_type,num_active_categories,expected_output_type,heart_rate,generated_answer,original_report,waveform_npy_id,gender_y,age_at_ecg_y,rr_interval_y,p_onset,p_end,qrs_onset,qrs_end,t_end,p_axis,qrs_axis,t_axis,new_PatientID,npy_id
0,/media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mimic,40000079.npy,/media/data1/ravram/MIMIC-IV/1.0/files/p1636/p16368287/s40000079/40000079.npy,M,68,909,Describe all ECG abnormalities present.,interpretation,1.0,interpretation,3,full_report,66.0,Sinus rhythm (HR: 66.0 bpm);Inferior and anterior ST-T changes are nonspecific;Borderline ECG,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,40000079,M,68,909,40,168,240,340,620,54,32,-11,16368287,40000079
1,/media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mimic,40000079.npy,/media/data1/ravram/MIMIC-IV/1.0/files/p1636/p16368287/s40000079/40000079.npy,M,68,909,Generate JSON representation of ECG abnormalities,json_interpretation,0.9,json,3,full_report,66.0,"{""RHYTHM"":[""Sinusal"",""Regular""],""INFARCT_ISCHEMIA"":[""ST depression_inferior_II_III_aVF"",""ST depression_anterior_V3-V4""],""OTHER"":[""T wave inversion_inferior_II_III_aVF"",""Monomorph"",""T wave inversio...",Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,40000079,M,68,909,40,168,240,340,620,54,32,-11,16368287,40000079
2,/media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mimic,40000079.npy,/media/data1/ravram/MIMIC-IV/1.0/files/p1636/p16368287/s40000079/40000079.npy,M,68,909,What are all the abnormalities in this complex ECG?,interpretation_complex,0.9,interpretation,3,full_report,66.0,Sinus rhythm (HR: 66.0 bpm);Inferior and anterior ST-T changes are nonspecific;Borderline ECG,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,40000079,M,68,909,40,168,240,340,620,54,32,-11,16368287,40000079
3,/media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mimic,40000079.npy,/media/data1/ravram/MIMIC-IV/1.0/files/p1636/p16368287/s40000079/40000079.npy,M,68,909,Are there pathological Q waves?,category_infarct_ischemia,0.8,category,3,category_specific,66.0,No - no evidence of q waves,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,40000079,M,68,909,40,168,240,340,620,54,32,-11,16368287,40000079
4,/media/data1/datasets/MIMIC-IV/adjusted_signals/test/40000079.npy,Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mimic,40000079.npy,/media/data1/ravram/MIMIC-IV/1.0/files/p1636/p16368287/s40000079/40000079.npy,M,68,909,Are there ST depressions in any leads?,localization_st_depression,0.7,localization,3,general,66.0,"Yes - st depression in anterior leads V3-V4; inferior leads II, III, aVF",Sinus rhythm;Inferior and anterior ST-T changes are nonspecific;Borderline ECG,40000079,M,68,909,40,168,240,340,620,54,32,-11,16368287,40000079